# ADO Pipeline YAML for ARM Template Deployment
trigger:
- main  # Set the branch that triggers the pipeline

pool:
  vmImage: 'windows-latest'  # Use an appropriate build agent image

jobs:
- job: DeployARMTemplates
  displayName: 'Deploy ARM Templates' # custom name for the task
  steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      azureResourceManagerConnection: 'ARM_TEMPLATE_SERVICE_CONNECTION'  # Replace with your Azure service connection name 
      subscriptionId: '540c5a3c-b29f-44d5-ada5-e8ffca6ff9e5'  # Replace with your Azure subscription ID
      resourceGroupName: 'ARM_Template_Test'
      location: 'US-east'  # Replace with your target Azure region
      csmFile: 'AppService.json'  # Replace with the path to your ARM template JSON file
      deploymentMode: 'Incremental'  # Choose 'Incremental' or 'Complete' deployment mode
    displayName: 'AppService + AppServicePlan'
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      azureResourceManagerConnection: 'ARM_TEMPLATE_SERVICE_CONNECTION'  # Replace with your Azure service connection name 
      subscriptionId: '540c5a3c-b29f-44d5-ada5-e8ffca6ff9e5'  # Replace with your Azure subscription ID
      resourceGroupName: 'ARM_Template_Test'
      location: 'US-east'  # Replace with your target Azure region
      csmFile: 'KeyVault.json'  # Replace with the path to your Key Vault ARM template JSON file
      deploymentMode: 'Incremental'  # Choose 'Incremental' or 'Complete' deployment mode
    displayName: 'KeyVault'
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      azureResourceManagerConnection: 'ARM_TEMPLATE_SERVICE_CONNECTION'  # Replace with your Azure service connection name 
      subscriptionId: '540c5a3c-b29f-44d5-ada5-e8ffca6ff9e5'  # Replace with your Azure subscription ID
      resourceGroupName: 'ARM_Template_Test'
      location: 'US-east'  # Replace with your target Azure region
      csmFile: 'azuredeploy.json'  # Replace with the path to your Storage Account ARM template JSON file
      deploymentMode: 'Incremental'  # Choose 'Incremental' or 'Complete' deployment mode
    displayName: 'AzureDeploy'

  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      azureResourceManagerConnection: 'ARM_TEMPLATE_SERVICE_CONNECTION'  # Replace with your Azure service connection name 
      subscriptionId: '540c5a3c-b29f-44d5-ada5-e8ffca6ff9e5'  # Replace with your Azure subscription ID
      resourceGroupName: 'ARM_Template_Test'
      location: 'US-east'  # Replace with your target Azure region
      csmFile: 'Storage.json'  # Replace with the path to your Storage Account ARM template JSON file
      deploymentMode: 'Incremental'  # Choose 'Incremental' or 'Complete' deployment mode
    displayName: 'Storage'
