
trigger:
- main  # Set the branch that triggers the pipeline

variables:
  # Define variables for Azure service connection and subscription ID
  azureServiceConnection: 'ARM_TEMPLATE_SERVICE_CONNECTION'
  azureSubscriptionId: '540c5a3c-b29f-44d5-ada5-e8ffca6ff9e5' 

  # Define variables for resource group, location, and ARM template file paths
  resourceGroupName: 'ARM_Template_Test'
  azureRegion: 'US-east' 
  appServiceTemplate: 'AppService.json'  
  keyVaultTemplate: 'KeyVault.json'    
  storageTemplate: 'Storage.json' 
  sqlServer: 'talatitestserver.json'

pool:
  vmImage: 'windows-latest'  

jobs:
- job: DeployARMTemplates
  displayName: 'Deploy ARM Templates' # custom name 
  steps:
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      azureResourceManagerConnection: $(azureServiceConnection)
      subscriptionId: $(azureSubscriptionId)
      resourceGroupName: $(resourceGroupName)
      location: $(azureRegion)
      csmFile: $(appServiceTemplate)
      deploymentMode: 'Incremental'  
    displayName: 'AppService + AppServicePlan'
  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      azureResourceManagerConnection: $(azureServiceConnection)
      subscriptionId: $(azureSubscriptionId)
      resourceGroupName: $(resourceGroupName)
      location: $(azureRegion)
      csmFile: $(keyVaultTemplate)
      deploymentMode: 'Incremental'  
    displayName: 'KeyVault'

  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      azureResourceManagerConnection: $(azureServiceConnection)
      subscriptionId: $(azureSubscriptionId)
      resourceGroupName: $(resourceGroupName)
      location: $(azureRegion)
      csmFile: $(storageTemplate)
      deploymentMode: 'Incremental' 
    displayName: 'Storage'

  - task: AzureResourceManagerTemplateDeployment@3
    inputs:
      azureResourceManagerConnection: $(azureServiceConnection)
      subscriptionId: $(azureSubscriptionId)
      resourceGroupName: $(resourceGroupName)
      location: $(azureRegion)
      csmFile: $(sqlServer)
      deploymentMode: 'Incremental' 
    displayName: 'Talati SQL Server'
